// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkFwJNUhQCbl31l_WnvqAEvzxfiAaNV58',
    appId: '1:854425800246:web:0bf617320c471365f71297',
    messagingSenderId: '854425800246',
    projectId: 'unistack-f3bc5',
    authDomain: 'unistack-f3bc5.firebaseapp.com',
    storageBucket: 'unistack-f3bc5.firebasestorage.app',
    measurementId: 'G-EL35KRLERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaIODAHWm77yfV6Ty-05bkORS8mg9NbI',
    appId: '1:854425800246:android:385470c938219ee8f71297',
    messagingSenderId: '854425800246',
    projectId: 'unistack-f3bc5',
    storageBucket: 'unistack-f3bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmA_ZbC2vD8Laf7K_0kZTknzBK3F1LMr4',
    appId: '1:854425800246:ios:a4e603a272c90d11f71297',
    messagingSenderId: '854425800246',
    projectId: 'unistack-f3bc5',
    storageBucket: 'unistack-f3bc5.firebasestorage.app',
    iosBundleId: 'com.example.fastflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmA_ZbC2vD8Laf7K_0kZTknzBK3F1LMr4',
    appId: '1:854425800246:ios:a4e603a272c90d11f71297',
    messagingSenderId: '854425800246',
    projectId: 'unistack-f3bc5',
    storageBucket: 'unistack-f3bc5.firebasestorage.app',
    iosBundleId: 'com.example.fastflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkFwJNUhQCbl31l_WnvqAEvzxfiAaNV58',
    appId: '1:854425800246:web:f151546f7fa0c32af71297',
    messagingSenderId: '854425800246',
    projectId: 'unistack-f3bc5',
    authDomain: 'unistack-f3bc5.firebaseapp.com',
    storageBucket: 'unistack-f3bc5.firebasestorage.app',
    measurementId: 'G-WBRFEF8N4X',
  );
}
